services:
  app:
    image: sep:online-V1.1.0
    ports:
      - "714:714"
    depends_on:
      - db
  db:
    image: postgres:15.6
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: bsbflsgxh..
      POSTGRES_DB: sep
    ports:
      - "5432:5432"