services:
  app:
    image: sep:online-V0.0.6
    ports:
      - "714:714"
    depends_on:
      - db
  db:
    image: postgres:15.6
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: bsbflsgxh..
      POSTGRES_DB: sep
    ports:
      - "5432:5432"
  web:
    image: sep-web:online-V0.1.2
    ports:
      - "8080:80"
    depends_on:
      - app